import { build } from "esbuild";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import * as Y from "yjs";

const root = dirname(fileURLToPath(import.meta.url));
const output = resolve(root, "../src/main/resources/crdt");
await mkdir(output, { recursive: true });

await build({
  absWorkingDir: root,
  entryPoints: ["src/project-document.js"],
  outfile: resolve(output, "yjs-projector.js"),
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2022",
  alias: { "lib0/webcrypto": "./src/webcrypto-adapter.js" },
  minify: true,
  legalComments: "inline",
  banner: { js: "// Generated by search-content/crdt-js/build.mjs. Do not edit." },
});

const notices = [];
for (const [name, license] of [["yjs", "LICENSE"], ["lib0", "LICENSE"], ["js-base64", "LICENSE.md"]]) {
  const packageRoot = resolve(root, "node_modules", name);
  const metadata = JSON.parse(await readFile(resolve(packageRoot, "package.json"), "utf8"));
  notices.push(`${name} ${metadata.version}\n${await readFile(resolve(packageRoot, license), "utf8")}`);
}
await writeFile(resolve(output, "THIRD-PARTY-NOTICES.txt"), notices.join("\n\n"));

// Deterministic input used by the production runtime's startup readiness check.
const doc = new Y.Doc({ guid: "projection-startup" });
doc.clientID = 1;
try {
  const content = doc.getText("content");
  content.insert(0, "# 문서\nHello");
  const baseState = Buffer.from(Y.encodeStateAsUpdate(doc)).toString("base64");
  const vector = Y.encodeStateVector(doc);
  doc.transact(() => {
    content.delete(5, 5);
    content.insert(5, "안녕 👋\n```java\nint n = 1;\n```");
  });
  await writeFile(resolve(output, "startup.json"), JSON.stringify({
    baseState,
    updates: [Buffer.from(Y.encodeStateAsUpdate(doc, vector)).toString("base64")],
    expectedContent: content.toString(),
  }, null, 2) + "\n");
} finally {
  doc.destroy();
}
